version: 3
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTEGRES_USER=teste
      - POSTEGRES_PASSWORD=teste
      - POSTEGRES_DB=teste
    networks:
      - app_networks
  nodejs_app:
    build: .
    container_name: node_app
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=$DATABASE_URL
    ports: 
      - 80:3000
    networks:
      - app_networks
volumes:
  postgres_data:
networks:
  app_networks:
    driver: bridge
  