version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nodejs_app:
    build: .
    container_name: node_app
    environment:
      DATABASE_URL: postgres://teste:teste@postgres_db:5432/biblioteca?schema=public
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
    ports:
      - 80:3000
    networks:
      - app_network

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - nodejs_app
  #   networks:
  #     - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge