version: '3'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: teste
      POSTGRES_PASSWORD: teste
      POSTGRES_DB: teste
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  nodejs_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: node_app
    depends_on:
      - postgres
    volumes:
      - ./app:/usr/src/app
    expose:
      - "3000"
    networks:
      - app_network

  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: nginx_server
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - nodejs_app
  #   networks:
  #     - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge